// Mock data to use when the API is down
import { Movie } from "@/types/movie";

export const mockTrendingMovies: Movie[] = [
  {
    id: 1,
    title: "The Matrix",
    overview: "A computer hacker learns about the true nature of reality and his role in the war against its controllers.",
    poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop_path: "/icmmSD4vTTDKOq2vvdulafONZBT.jpg",
    release_date: "1999-03-30",
    vote_average: 8.2,
    vote_count: 22465,
    adult: false,
    genre_ids: [28, 878],
    original_language: "en",
    original_title: "The Matrix",
    popularity: 100.5,
    video: false
  },
  {
    id: 2,
    title: "Inception",
    overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    poster_path: "/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    backdrop_path: "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    release_date: "2010-07-16",
    vote_average: 8.4,
    vote_count: 30545,
    adult: false,
    genre_ids: [28, 878, 53],
    original_language: "en",
    original_title: "Inception",
    popularity: 95.3,
    video: false
  },
  {
    id: 3,
    title: "Interstellar",
    overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    release_date: "2014-11-05",
    vote_average: 8.4,
    vote_count: 26925,
    adult: false,
    genre_ids: [12, 18, 878],
    original_language: "en",
    original_title: "Interstellar",
    popularity: 90.2,
    video: false
  },
  {
    id: 4,
    title: "Pulp Fiction",
    overview: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    release_date: "1994-10-14",
    vote_average: 8.5,
    vote_count: 23234,
    adult: false,
    genre_ids: [53, 80],
    original_language: "en",
    original_title: "Pulp Fiction",
    popularity: 88.7,
    video: false
  },
  {
    id: 5,
    title: "Dune",
    overview: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.",
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    backdrop_path: "/jYEW5xZkZk2WTrdbMGAPFuBqbDS.jpg",
    release_date: "2021-09-15",
    vote_average: 8.0,
    vote_count: 7812,
    adult: false,
    genre_ids: [878, 12],
    original_language: "en",
    original_title: "Dune",
    popularity: 87.1,
    video: false
  }
];

export const mockPopularMovies: Movie[] = [
  {
    id: 6,
    title: "The Shawshank Redemption",
    overview: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    release_date: "1994-09-23",
    vote_average: 8.7,
    vote_count: 21740,
    adult: false,
    genre_ids: [18, 80],
    original_language: "en",
    original_title: "The Shawshank Redemption",
    popularity: 85.9,
    video: false
  },
  {
    id: 7,
    title: "The Godfather",
    overview: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdrop_path: "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
    release_date: "1972-03-14",
    vote_average: 8.7,
    vote_count: 16379,
    adult: false,
    genre_ids: [18, 80],
    original_language: "en",
    original_title: "The Godfather",
    popularity: 84.4,
    video: false
  },
  {
    id: 8,
    title: "The Dark Knight",
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_path: "/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
    release_date: "2008-07-16",
    vote_average: 8.5,
    vote_count: 27965,
    adult: false,
    genre_ids: [28, 80, 18],
    original_language: "en",
    original_title: "The Dark Knight",
    popularity: 83.2,
    video: false
  },
  {
    id: 9,
    title: "Fight Club",
    overview: "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.",
    poster_path: "/8kNruSfhk5IoE4eZOc4UpvDn6tq.jpg",
    backdrop_path: "/rr7E0NoGKxvbkb89eR1GwfoYjpA.jpg",
    release_date: "1999-10-15",
    vote_average: 8.4,
    vote_count: 24564,
    adult: false,
    genre_ids: [18],
    original_language: "en",
    original_title: "Fight Club",
    popularity: 80.1,
    video: false
  },
  {
    id: 10,
    title: "Forrest Gump",
    overview: "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
    poster_path: "/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
    backdrop_path: "/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
    release_date: "1994-07-06",
    vote_average: 8.5,
    vote_count: 23854,
    adult: false,
    genre_ids: [35, 18, 10749],
    original_language: "en",
    original_title: "Forrest Gump",
    popularity: 78.5,
    video: false
  }
];
