#!/bin/bash

echo "🐛 Debugging TV Show Buttons on Home Page"
echo "=========================================="

echo ""
echo "🔍 Debug Checklist:"
echo "==================="
echo ""
echo "1. 🌐 Open Browser Developer Tools:"
echo "   - Press F12 or Ctrl+Shift+I"
echo "   - Go to Console tab"
echo ""
echo "2. 🏠 Navigate to Home Page:"
echo "   - Go to: http://localhost:3000"
echo "   - Scroll to TV show sections"
echo ""
echo "3. 🎯 Test Button Interactions:"
echo "   - Hover over a TV show card to reveal buttons"
echo "   - Try clicking each button while watching console"
echo "   - Look for these console messages:"
echo "     • 'Adding to favorites: [ID] [Name]'"
echo "     • 'Adding to watchlist: [ID] [Name]'"
echo "     • Authentication errors"
echo "     • JavaScript errors"
echo ""
echo "4. 🔐 Check Authentication:"
echo "   - Are you logged in?"
echo "   - Do you see login prompts when clicking buttons?"
echo "   - Try logging in and testing again"
echo ""
echo "5. 🎭 Compare with Working Pages:"
echo "   - Go to TV Shows page: http://localhost:3000/tv-shows"
echo "   - Test the same buttons there"
echo "   - Do they work on TV Shows page but not Home page?"
echo ""
echo "6. 🖱️ Test Click Areas:"
echo "   - Make sure you're clicking the button, not the card"
echo "   - Try hovering longer before clicking"
echo "   - Check if buttons are visually appearing"
echo ""
echo "📋 Common Issues to Check:"
echo "========================="
echo ""
echo "❌ Buttons not appearing on hover:"
echo "   - CSS/animation timing issue"
echo "   - Hover state not triggering"
echo ""
echo "❌ Buttons visible but not clickable:"
echo "   - Event propagation issue"
echo "   - Z-index/overlay blocking clicks"
echo "   - JavaScript errors"
echo ""
echo "❌ Buttons clickable but no action:"
echo "   - Authentication required"
echo "   - TV show format conversion issue"
echo "   - Preferences system not working"
echo ""
echo "❌ Console errors:"
echo "   - Missing dependencies"
echo "   - API endpoint issues"
echo "   - Type conversion problems"
echo ""
echo "🔧 Debug Commands:"
echo "=================="
echo ""
echo "In browser console, try these commands:"
echo ""
echo "// Check if UserPreferences context is available"
echo "console.log('Auth:', window.React?.useContext);"
echo ""
echo "// Check if buttons exist in DOM"
echo "document.querySelectorAll('button[aria-label*=\"favorites\"]').length"
echo "document.querySelectorAll('button[aria-label*=\"watchlist\"]').length"
echo ""
echo "// Check for click event listeners"
echo "Array.from(document.querySelectorAll('button')).forEach(btn => {"
echo "  console.log(btn.getAttribute('aria-label'), btn.onclick);"
echo "});"
echo ""
echo "🎯 Expected Behavior:"
echo "===================="
echo "1. Hover over TV show card → Buttons appear"
echo "2. Click favorites button → Heart turns red + toast message"
echo "3. Click watchlist button → Plus becomes checkmark + toast message"
echo "4. Go to My List page → TV shows appear in respective tabs"
echo ""
echo "📞 If buttons still don't work:"
echo "=============================="
echo "1. Check if the issue is specific to home page"
echo "2. Verify buttons work on TV Shows page"
echo "3. Look for console errors"
echo "4. Check if authentication is working"
echo "5. Verify TV show data format is correct"
