#!/bin/bash

echo "🧪 Testing TV Show Card Favorites and Watchlist Functionality"
echo "=============================================================="

# Check if the server is running
echo "📡 Checking server connection..."

if curl -f -s http://localhost:5000/api/health > /dev/null; then
    echo "✅ Server is running"
else
    echo "❌ Server is not running. Please start the development server first:"
    echo "   npm run dev"
    exit 1
fi

echo ""
echo "🎯 Testing TV Show Cards with Action Buttons"
echo "============================================="
echo ""
echo "📋 Test Instructions:"
echo "====================="
echo "1. Open http://localhost:3000 in your browser"
echo "2. Navigate to the TV Shows page"
echo "3. Switch to 'Grid view' using the grid button"
echo "4. Hover over any TV show card"
echo "5. Verify that action buttons appear:"
echo "   - ▶️  Play button (red) - should navigate to TV show details"
echo "   - ➕ Add to list button (gray) - should add to watchlist"
echo "   - ❤️  Favorites button (gray) - should add to favorites"
echo "   - ℹ️  Info button (gray) - should navigate to TV show details"
echo ""
echo "🧪 Detailed Test Scenarios:"
echo "==========================="
echo ""
echo "A. Test TV Show Grid Cards:"
echo "   1. Go to TV Shows page"
echo "   2. Click the grid view button (top right)"
echo "   3. Hover over any TV show card"
echo "   4. You should see 4 action buttons appear on hover"
echo "   5. Test each button to ensure it works"
echo ""
echo "B. Test Add to Favorites (Grid View):"
echo "   1. Hover over a TV show card in grid view"
echo "   2. Click the heart (❤️) button"
echo "   3. Button should turn red and filled"
echo "   4. Go to My List page and check Favorites tab"
echo "   5. TV show should appear in favorites"
echo ""
echo "C. Test Add to Watchlist (Grid View):"
echo "   1. Hover over a TV show card in grid view"
echo "   2. Click the plus (➕) button"
echo "   3. Button should show a checkmark and turn white"
echo "   4. Go to My List page and check Watchlist tab"
echo "   5. TV show should appear in watchlist"
echo ""
echo "D. Test List View (Already Working):"
echo "   1. Switch to list view on TV Shows page"
echo "   2. Verify HorizontalTVShowCard still works with buttons"
echo "   3. Both grid and list views should now have action buttons"
echo ""
echo "E. Test Other Pages:"
echo "   1. Check Home page TV show sliders (should use HorizontalTVShowCard)"
echo "   2. Check Genre pages if they show TV shows"
echo "   3. Verify all TV show cards now have action buttons"
echo ""
echo "🔍 What to Look For:"
echo "==================="
echo "✅ Grid view TV show cards show action buttons on hover"
echo "✅ Favorites button turns red when favorited"
echo "✅ Watchlist button shows checkmark when added"
echo "✅ TV shows appear in My List page after adding"
echo "✅ Buttons work without navigating away (event.stopPropagation)"
echo "✅ Login prompt appears if not authenticated"
echo ""
echo "❌ Issues to Report:"
echo "- Buttons not appearing on hover"
echo "- Buttons not working (navigation happens instead)"
echo "- TV shows not appearing in My List"
echo "- Console errors when clicking buttons"
echo ""
echo "📝 Notes:"
echo "========="
echo "- You must be logged in to use favorites/watchlist functionality"
echo "- Grid view cards now match the functionality of list view cards"
echo "- Both grid and list views should work seamlessly"
echo "- Action buttons only appear on hover to keep the design clean"
