#!/bin/bash

echo "🔧 Testing TV Show Button Fixes"
echo "================================"

# Check if the server is running
echo "📡 Checking server connection..."

if curl -f -s http://localhost:5000/api/health > /dev/null; then
    echo "✅ Server is running"
else
    echo "❌ Server is not running. Please start the development server first:"
    echo "   npm run dev"
    exit 1
fi

echo ""
echo "🎯 Fixed Issues:"
echo "================"
echo "✅ TV shows now get converted to compatible format before adding to favorites/watchlist"
echo "✅ Added 'title' field mapping from 'name' field for TV shows"
echo "✅ Fixed both HorizontalTVShowCard and TVShowCard components"
echo "✅ Fixed addToWatchHistory calls for TV shows"
echo ""
echo "🧪 Test Instructions:"
echo "====================="
echo ""
echo "1. 🏠 HOME PAGE TEST:"
echo "   - Go to: http://localhost:3000"
echo "   - Scroll to 'Trending TV Shows' or 'Popular TV Shows' sections"
echo "   - Hover over any TV show card (should show buttons)"
echo "   - Click the ❤️ (heart) button to add to favorites"
echo "   - Click the ➕ (plus) button to add to watchlist"
echo "   - Verify buttons change state (heart turns red, plus becomes checkmark)"
echo ""
echo "2. 📺 TV SHOWS PAGE TEST:"
echo "   - Go to: http://localhost:3000/tv-shows"
echo "   - Test both Grid View and List View:"
echo "     • Grid View: Hover over cards, test action buttons"
echo "     • List View: Hover over horizontal cards, test action buttons"
echo "   - Both views should now work correctly"
echo ""
echo "3. 🎭 GENRE PAGES TEST:"
echo "   - Go to any genre page that shows TV shows"
echo "   - Test TV show card buttons"
echo ""
echo "4. 📋 MY LIST PAGE VERIFICATION:"
echo "   - Go to: http://localhost:3000/my-list"
echo "   - Check 'Favorites' tab - should show TV shows you favorited"
echo "   - Check 'Watchlist' tab - should show TV shows you added to list"
echo "   - TV shows should display with correct titles"
echo ""
echo "🔍 What to Look For:"
echo "==================="
echo "✅ TV show buttons work without errors"
echo "✅ TV shows appear in My List after adding"
echo "✅ Button states reflect current status"
echo "✅ No console errors when clicking buttons"
echo "✅ Toast notifications appear when adding/removing"
echo ""
echo "❌ Issues to Report:"
echo "- Buttons still not working"
echo "- TV shows not appearing in My List"
echo "- Console errors (check browser dev tools)"
echo "- Button states not updating correctly"
echo ""
echo "📝 Technical Fix Details:"
echo "========================="
echo "Problem: TV shows have 'name' field, but preferences system expects 'title'"
echo "Solution: Convert TV show objects to compatible format before saving:"
echo ""
echo "// Before (broken):"
echo "addToFavorites(show);"
echo ""
echo "// After (fixed):"
echo "const favoriteFormat = {"
echo "  ...show,"
echo "  title: show.name  // Map name to title"
echo "};"
echo "addToFavorites(favoriteFormat);"
echo ""
echo "🎉 This fix ensures TV shows work seamlessly with the unified preferences system!"
