#!/bin/bash

echo "🧪 Testing TV Show Horizontal Card Button Functionality"
echo "======================================================="

# Check if the server is running
echo "📡 Checking server connection..."

if curl -f -s http://localhost:5000/api/health > /dev/null; then
    echo "✅ Server is running"
elif curl -f -s http://localhost:3000 > /dev/null; then
    echo "✅ Client server is running on port 3000"
else
    echo "❌ No server running. Please start with:"
    echo "   npm run dev"
    echo ""
    echo "Then run this test again."
    exit 1
fi

echo ""
echo "🔍 DEBUGGING TV SHOW BUTTON ISSUES"
echo "=================================="
echo ""
echo "The buttons have console logging built in. Here's what to check:"
echo ""
echo "1. 🌐 Open your browser to http://localhost:3000"
echo "2. 🛠️  Open Developer Tools (F12)"
echo "3. 📊 Go to the Console tab"
echo "4. 🏠 Navigate to the Home page"
echo "5. 📺 Find the TV show sliders (Trending TV Shows, Popular TV Shows)"
echo "6. 🖱️  Hover over a TV show card to see the action buttons"
echo "7. 🔘 Click the buttons and watch the console"
echo ""
echo "🔍 WHAT TO LOOK FOR IN CONSOLE:"
echo "=============================="
echo ""
echo "✅ WORKING - You should see:"
echo "   📺 TV Show Favorite button clicked: [Show Name] [ID]"
echo "   💖 Adding to favorites: [ID]"
echo "   OR"
echo "   📺 TV Show Watchlist button clicked: [Show Name] [ID]" 
echo "   ➕ Adding to watchlist: [ID]"
echo ""
echo "❌ NOT WORKING - You might see:"
echo "   🚫 Card click blocked - button was clicked"
echo "   🔗 Card click - navigating to TV show: [ID]"
echo "   (This means card navigation is happening instead of button action)"
echo ""
echo "❌ AUTHENTICATION ISSUES:"
echo "   ❌ User not authenticated for favorites"
echo "   ❌ User not authenticated for watchlist"
echo "   (You need to log in first)"
echo ""
echo "🎯 SPECIFIC TEST STEPS:"
echo "======================"
echo ""
echo "Test 1 - Authentication Check:"
echo "1. Make sure you're logged in to your account"
echo "2. If not logged in, the buttons should show login prompts"
echo ""
echo "Test 2 - Favorites Button:"
echo "1. Find a TV show card in the home page sliders"
echo "2. Hover to show buttons"
echo "3. Click the ❤️ (heart) button"
echo "4. Check console for: '📺 TV Show Favorite button clicked'"
echo "5. Button should turn red if successful"
echo ""
echo "Test 3 - Watchlist Button:"
echo "1. Find a TV show card in the home page sliders"
echo "2. Hover to show buttons"
echo "3. Click the ➕ (plus) button"
echo "4. Check console for: '📺 TV Show Watchlist button clicked'"
echo "5. Button should show checkmark if successful"
echo ""
echo "Test 4 - Verify in My List:"
echo "1. Go to http://localhost:3000/my-list"
echo "2. Check 'Favorites' tab for TV shows you favorited"
echo "3. Check 'Watchlist' tab for TV shows you added"
echo ""
echo "🚨 COMMON ISSUES TO CHECK:"
echo "=========================="
echo ""
echo "Issue 1: Buttons not clickable"
echo "- Check if you can see the buttons on hover"
echo "- Try clicking directly on the icon inside the button"
echo "- Check if console shows any errors"
echo ""
echo "Issue 2: Card navigation happens instead"
echo "- Console shows 'Card click - navigating to TV show'"
echo "- This means event propagation isn't working"
echo "- Button clicks should show 'Card click blocked'"
echo ""
echo "Issue 3: Authentication required"
echo "- Console shows 'User not authenticated'"
echo "- Log in to your account first"
echo ""
echo "Issue 4: UserPreferences hook issues"
echo "- Check for any red errors in console"
echo "- Look for network errors in Network tab"
echo ""
echo "📝 WHAT TO REPORT:"
echo "=================="
echo "Please report what you see in the console when clicking the buttons:"
echo "- Exact console messages"
echo "- Whether you're logged in"
echo "- Which browser you're using"
echo "- Whether the buttons are visible on hover"
echo ""
echo "This will help identify if it's:"
echo "- Event propagation issue"
echo "- Authentication issue"
echo "- UserPreferences hook issue"
echo "- CSS/visibility issue"
