#!/bin/bash

echo "🎨 Testing YMovies Logo Font Updates"
echo "===================================="
echo ""
echo "Testing Akaya Kanadaka font application to YMovies branding:"
echo ""
echo "✅ WHAT HAS BEEN UPDATED:"
echo "- Navigation bar logo: YMovies text now uses Akaya Kanadaka font"
echo "- Footer logo: YMovies text now uses Akaya Kanadaka font"
echo "- Font properly configured in index.css and tailwind.config.ts"
echo ""
echo "🌐 TO TEST:"
echo "1. Start the development server: npm run dev"
echo "2. Open http://localhost:3000"
echo "3. Check the navigation bar at the top - 'YMovies' should display in Akaya Kanadaka font"
echo "4. Scroll to the bottom and check the footer - 'YMovies' should also use the same font"
echo ""
echo "🔍 WHAT TO LOOK FOR:"
echo "- The YMovies text should appear more stylized and decorative"
echo "- Both navbar and footer should use the same font"
echo "- Font should load from /fonts/AkayaKanadaka-Regular.ttf"
echo ""
echo "🚨 IF THE FONT DOESN'T SHOW:"
echo "- Check browser console for font loading errors"
echo "- Verify the font file exists in public/fonts/"
echo "- Try hard refresh (Ctrl+F5 or Cmd+Shift+R)"
echo ""
echo "📝 Technical Details:"
echo "- Font family: 'Akaya Kanadaka'"
echo "- Font file: AkayaKanadaka-Regular.ttf"
echo "- Tailwind class: font-akaya"
echo "- Applied to: .navbar YMovies logo and .footer YMovies logo"
